name: init

on: push

jobs:
    init:
        runs-on: ubuntu-latest
        if: github.repository != 'designcontainer/wpe-template'
        steps:
            - uses: actions/checkout@v2
            - name: Setup Template
              uses: designcontainer/wpe-template-helper@master
              with:
                  github_token: ${{ secrets.BOT_TOKEN }}
                  workflow_file: init.yml
                  theme_repo: designcontainer/dc-skeleton
                  committer_username: designcontainer-bot
                  committer_email: tech@designcontainer.no
                  commit_message: 'CI: Repo initialization for WP Engine install'
