name: Template initialization helper

on: create

jobs:
    build:
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Template
              uses: designcontainer/wpe-template-helper@master
              with:
                  github_token: ${{ secrets.BOT_TOKEN }}
                  theme_repo: designcontainer/dc-skeleton
                  committer_username: designcontainer-bot
                  committer_email: tech@designcontainer.no
                  commit_message: 'CI: Repo initialization for WP Engine install'
