# This action is centrally managed in https://github.com/designcontainer/.github/
# Don't make changes to this file outside of the .github repository!
# Files will get overwritten with changes made to the same file in the above mentioned repository.

name: Deploy to WP Engine & Notify Slack

on:
    push:
        branches:
            - master
            - staging
            - development

jobs:
    build:
        if: "github.event.repository.name != '.github' && github.event.repository.name != 'wpe-template' && !contains(github.event.head_commit.message, '[skip deploy]') && !contains(github.event.head_commit.message, '[skip-deploy]')"
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Get install for deployer by branch
              id: get_install
              uses: designcontainer/wpe-install-by-branch@master
              with:
                  wpe_api_key_pub: ${{ secrets.WPE_API_USERNAME }}
                  wpe_api_key_priv: ${{ secrets.WPE_API_PASSWORD }}

            - uses: actions/checkout@v2
            - name: GitHub Deploy to WP Engine
              uses: wpengine/github-action-wpe-site-deploy@v1.3
              env:
                  WPE_ENV_NAME: ${{ steps.get_install.outputs.install }}
                  WPE_SSHG_KEY_PUBLIC: ${{ secrets.WPE_PUBLIC_KEY_NAME }}
                  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_PRIVATE_KEY_NAME }}

            - uses: actions/checkout@v2
            - name: Slack Notification
              uses: rtCamp/action-slack-notify@v2
              env:
                  SLACK_CHANNEL: dc-github
                  SLACK_COLOR: ${{job.status}}
                  SLACK_ICON: https://github.com/designcontainer.png?size=48
                  SLACK_TITLE: Commit message
                  SLACK_USERNAME: DC Github Bot
                  SLACK_FOOTER: This commit has been deployed to ${{ github.event.repository.name }}
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                  MSG_MINIMAL: commit
